project:
  type: website

website:
  title: "Analyst Network North East"
  navbar:
    right:
      - index.qmd
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/company/analyst-network-north-east/about/
      - icon: twitter
        href: https://twitter.com/AnalystNetNE
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto

